### ISSUE TITLE
Исправь

### ISSUE THREAD

**Issue by Act1nium** [jedi1150/number-systems#31]
Привет. Снизу по умолчанию основание 3. Если вводить число допустим в десятичной СС, а потом поменять основание на отличное от 3, то число так и продолжает отображаться в троичной СС.

**Comment by jedi1150** [comment]
Привет!
Спасибо за фидбек, обязательно посмотрю!

**Comment by Act1nium** [comment]
Тебе спасибо за такое классное приложение.
