### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Act1nium** [jedi1150/number-systems#43]
Привет. В последнее время заметил глобальную ошибку. Пример: вводим в 16 СС "A". Пишет, что она равна 36 в 10 СС, хотя она равна 10. Из-за данной ошибки очень частно выдает неверные ответы. Поискал бы сам ошибку, но за котлин не шарю.

**Comment by jedi1150** [comment]
Привет! Была проблема с регистром, в последнем матче фиксил эту проблему.

Спасибо что сообщил! 🙂
